project_id = "eyjyknyeknlpfgkiccyk"

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.send-newsletter-welcome]
verify_jwt = false

[functions.send-bulk-welcome-emails]
verify_jwt = false

[functions.get-customers]
verify_jwt = false